# Generated by Django 2.1.15 on 2021-11-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='freetext_answer_available',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
