# Generated by Django 2.1.15 on 2021-11-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_survey_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='free_text_answer',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
