# Generated by Django 2.1.15 on 2021-11-11 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20211108_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='surveys.Answer'),
        ),
    ]
